---
- name: Converge
  hosts: all
  become: true
  collections:
    - community.general
  vars:
    firewalld_managed: true
    firewalld_zones:
      - public:
        subnet: 10.1.0.0
        prefix: 24
        services_enabled:
          - ssh
      - lan:
        subnet: 10.1.1.0
        prefix: 24
        services_enabled:
          - ssh
      - vpn1:
        subnet: 10.5.0.0
        prefix: 16
        services_enabled:
          - ssh
      - vpn2:
        subnet: 10.10.0.0
        prefix: 16
        services_disabled:
          - ssh
  tasks:
    - name: Run role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
