---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yamllint.yml .
  ansible-lint molecule/default/converge.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      firewall:
        firewalld_managed: true
    host_vars:
      firewalld_zones:
        - public:
          subnet: 10.1.0.0
          prefix: 24
          services_enabled:
            - ssh
        - lan:
          subnet: 10.1.1.0
          prefix: 24
          services_enabled:
            - ssh
        - vpn1:
          subnet: 10.5.0.0
          prefix: 16
          services_enabled:
            - ssh
        - vpn2:
          subnet: 10.10.0.0
          prefix: 16
          services_disabled:
            - ssh
verifier:
  name: ansible
