---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Run when managed
      block:
        - name: Collect package facts
          package_facts:

        - name: Check firewalld package
          assert:
            that: "'firewalld' in ansible_facts.packages"

        - name: Collect service facts
          service_facts:

        - name: Check firewalld service is present
          assert:
            that: "'firewalld.service' in ansible_facts.services"

        - name: Check firewalld service is running
          assert:
            that: "ansible_facts.services['firewalld.service']['state'] == 'running'"

        - name: Check firewalld service is enabled
          assert:
            that: "ansible_facts.services['firewalld.service']['status'] == 'enabled'"

        - name: Collect sources of zone public
          command: firewall-cmd --zone=public --list-sources
          register: firewall_cmd_result
          when: true

        - name: Check wan (10.1.0.0/24) is in zone public
          assert:
            that: "firewall_cmd_result.stdout == '10.1.0.0.0/24'"
            fail_msg: "Current values: {{ firewall_cmd_result.stdout }}"

        - name: Collect sources of zone lan
          command: firewall-cmd --zone=lan --list-sources
          register: firewall_cmd_result
          when: true

        - name: Check lan (10.11.1.0/24) is in zone trlanusted
          assert:
            that: "firewall_cmd_result.stdout == '10.1.1.0/24'"
            fail_msg: "Current values: {{ firewall_cmd_result.stdout }}"

      when: firewalld_managed is defined
